### ISSUE TITLE
Trouble using Pyansys when importing a file

### ISSUE THREAD

**Issue by adityasga** [pyansys/pydpf-post#71]
Hello,
I've installed PyAnsys on an anaconda python 3.6.3 environment however anytime I try to import a file either using the post.load_solution (examples.multishells_rst) or using Model('ASimpleBar.rst'), I get a Win2Error: The system cannot find the file specified.

Some specifications about the computer and environment: 

Windows 10 Home (Version: 21H2)
Ansys Version: Ansys 2021 R1
All the packages running on my anaconda python 3.6.3 environment are attached.

[Packages.txt](https://github.com/pyansys/pydpf-post/files/8513112/Packages.txt)

So far the problem occurs anytime I try to import (whether it's using Post, Core (using Model),etc). The same error (Win2Error) is always encountered and this is the same error message I get regardless of whether I use Post or Core. Below is a screenshot of the error:

<img width="1570" alt="Screen Shot 2022-04-19 at 8 49 37 AM" src="https://user-images.githubusercontent.com/44749081/164007908-9ca6afeb-73ee-4766-9e70-908bc9ef5abb.png">

<img width="1579" alt="Screen Shot 2022-04-19 at 8 50 12 AM" src="https://user-images.githubusercontent.com/44749081/164007922-22ee916a-5195-4f55-b73a-eae21ba57870.png">

**Comment by PProfizi** [comment]
Hello @adityasga ,

One quick answer:
The [compatibility](https://dpfdocs.pyansys.com/getting_started/index.html#compatibility) segment of the doc states that for ANSYS2021R1, an ansys-dpf-core version of 0.2.* should be used, along with ansys.grpc.dpf 0.2.2
One thing you should do first is uninstall the current packages (dpf-core 0.4.1 and grpc.dpf 0.4.0 according to your packages.txt file) and install the versions compatible with your ANSYS installation.
Then, if it stil gives you a WinError2 file not found error, this might also be because file paths should be relative to the server executable of your ANSYS installation. I would suggest trying absolute paths to see if the problem persists.

I will then look into why the compatibility error message was not the first to pop, and why this error message is the one raised.

**Comment by adityasga** [comment]
Thanks @PProfizi. Will try that and get back to you!

**Comment by PProfizi** [comment]
Closing as stale, please reopen if still relevant.
